import { PageItemModel } from "@/models/PageItemModel";

export const sampleForm: PageItemModel = {
  description: null,
  overview: null,
  content: null,
  id: "76b70ac1-ea13-44a1-1123-08dc2864ac1a",
  languageCode: "en",
  status: "Active",
  name: "Form example",
  slug: "form-example",
  isConfirmed: true,
  customStyle: "",
  sections: [
    {
      id: "ed90dd06-c9c4-4fd0-c479-08dc2864ac22",
      listType: "Grid",
      customStyle: "",
      order: 0,
      blocks: [
        {
          id: "aaaaccc",
          blockType: "Image",
          imageUrl:
            "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
          imageThumbnailUrl:
            "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
          languageCode: "en",
          isConfirmed: true,
          order: 0,
          name: "image block",
          subtitle: "",
          medias: [],
        },
        {
          id: "f200a768-757b-41b8-9b79-08dc2864ac23",
          languageCode: "en",
          blockType: "Form",
          icon: null,
          customStyle:
            "flex flex-row flex-wrap gap-3 items-center justify-between",
          order: 1,
          name: "Why Choose Us?",
          subtitle: "A choice that makes the difference",
          description: null,
          overview: null,
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
          formItems: [
            {
              id: "a1",
              name: "Full Name",
              customStyle: "w-full",
              formItemType: "SingleLineText",
              placeholder: "Full Name",
              order: 0,
              required: true,
            },
            {
              id: "a2",
              name: "Specialty",
              customStyle: "w-full md:w-1/2",
              formItemType: "Select",
              placeholder: "Specialty",
              order: 1,
              required: true,
              options: [
                {
                  id: "a2-1",
                  name: "Specialty #1",
                  order: 0,
                },
                {
                  id: "a2-2",
                  name: "Specialty #2",
                  order: 0,
                },
                {
                  id: "a2-3",
                  name: "Specialty #3",
                  order: 0,
                },
              ],
            },
            {
              id: "a3",
              name: "Service",
              customStyle: "w-full md:w-1/2",
              formItemType: "Select",
              placeholder: "Service",
              order: 2,
              required: true,
              options: [
                {
                  id: "a3-1",
                  name: "Service #1",
                  order: 0,
                },
                {
                  id: "a3-2",
                  name: "Service #2",
                  order: 1,
                },
              ],
            },
            {
              id: "a4-email",
              name: "Email",
              customStyle: "w-full",
              placeholder: "Eamil Address",
              formItemType: "Email",
              required: true,
              order: 3,
            },
            {
              id: "a4-phone-number",
              name: "PhoneNumber",
              customStyle: "w-full",
              placeholder: "Phone number",
              formItemType: "PhoneNumber",
              required: false,
              order: 4,
            },
            {
              id: "a4",
              name: "How do you want to approach us?",
              formItemType: "CheckBox",
              customStyle: "w-full",
              placeholder: "",
              order: 5,
              options: [
                {
                  id: "a4-1",
                  name: "Online",
                  order: 1,
                },
                {
                  id: "a4-2",
                  name: "Offline",
                  order: 2,
                },
              ],
            },
            {
              id: "a5",
              name: "Do you agree to provide your personal information to contact you on our platform?",
              customStyle: "w-full",
              formItemType: "RadioButton",
              placeholder: "",
              order: 6,
              required: true,
              options: [
                {
                  id: "a5-1",
                  name: "Yes",
                  order: 0,
                },
                {
                  id: "a5-2",
                  name: "No",
                  order: 1,
                },
              ],
            },
            {
              id: "6",
              name: "Comment",
              customStyle: "w-full",
              formItemType: "MultiLineText",
              placeholder: "Comments",
              required: false,
              order: 5,
            },
          ],
        },
      ],
    },
    {
      id: "52bf3727-d6c5-486f-c47a-08dc2864ac22",
      listType: "Grid",
      customStyle: null,
      order: 1,
      blocks: [
        {
          id: "9a9e05f1-f781-4096-9b7a-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "fa-solid fa-square-check",
          customStyle: null,
          order: 0,
          name: "80+",
          subtitle: "World Class Doctors",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
        {
          id: "583ce159-3341-4d9e-9b7b-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "checkbox",
          customStyle: null,
          order: 1,
          name: "80+",
          subtitle: "Advanced Healthcare Technology",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
        {
          id: "37e3baad-0c45-43d2-9b7c-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "checkbox",
          customStyle: null,
          order: 2,
          name: "80+",
          subtitle: "Afforrdablility & Finacial Assistance",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
        {
          id: "4f9d3a19-bb9c-4466-9b7d-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "checkbox",
          customStyle: null,
          order: 3,
          name: "80+",
          subtitle: "Best Clinic Outcomes",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
      ],
    },
  ],
};
