import { PageItemModel } from "@/models/PageItemModel";

export const sample: PageItemModel = {
  customStyle: "",
  sections: [
    {
      id: "ed90dd06-c9c4-4fd0-c479-08dc2864ac22",
      listType: "None",
      customStyle: "",
      order: 0,
      blocks: [
        {
          id: "f200a768-757b-41b8-9b79-08dc2864ac23",
          languageCode: "en",
          blockType: "Title",
          icon: null,
          customStyle: null,
          order: 0,
          name: "Why Choose Us?",
          subtitle: "A choice that makes the difference",
          description: null,
          overview: null,
          content: null,
          isConfirmed: true,
          medias: [],
          links: [
            {
              id: "70a4975f-7e52-4610-8bb5-08dc2864ac24",
              languageCode: "en",
              linkType: "Button",
              name: "Enquiry Now",
              url: "https://icloudhospital.com/enquiry-now",
              isConfirmed: false,
              order: 0,
            },
            {
              id: "5001a592-75f6-4824-8bb6-08dc2864ac24",
              languageCode: "en",
              linkType: "Button",
              name: "Consultation Now",
              url: "https://icloudhospital.com/consultation-now",
              isConfirmed: false,
              order: 1,
            },
          ],
          locations: [],
        },
      ],
    },
    {
      id: "52bf3727-d6c5-486f-c47a-08dc2864ac22",
      listType: "Grid",
      customStyle: null,
      order: 1,
      blocks: [
        {
          id: "9a9e05f1-f781-4096-9b7a-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "fa-solid fa-square-check",
          customStyle: null,
          order: 0,
          name: "80+",
          subtitle: "World Class Doctors",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
        {
          id: "583ce159-3341-4d9e-9b7b-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "checkbox",
          customStyle: null,
          order: 1,
          name: "80+",
          subtitle: "Advanced Healthcare Technology",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
        {
          id: "37e3baad-0c45-43d2-9b7c-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "checkbox",
          customStyle: null,
          order: 2,
          name: "80+",
          subtitle: "Afforrdablility & Finacial Assistance",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
        {
          id: "4f9d3a19-bb9c-4466-9b7d-08dc2864ac23",
          languageCode: "en",
          blockType: "ListItem",
          icon: "checkbox",
          customStyle: null,
          order: 3,
          name: "80+",
          subtitle: "Best Clinic Outcomes",
          description: null,
          overview:
            "Culpa ad culpa ex exercitation quis aliqua elit amet amet veniam eiusmod ullamco.",
          content: null,
          isConfirmed: true,
          medias: [],
          links: [],
          locations: [],
        },
      ],
    },
    {
      id: "a959b52d-5ea8-4cce-c47b-08dc2864ac22",
      listType: "None",
      customStyle: null,
      order: 2,
      blocks: [
        {
          id: "d80e319f-d6a2-44d5-9b7e-08dc2864ac23",
          languageCode: "en",
          blockType: "About",
          icon: null,
          customStyle: null,
          order: 0,
          name: "",
          subtitle: "",
          description: null,
          overview: null,
          content:
            '<p><img src="https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp" alt="image" /></p><p>Consequat pariatur lorem sed officia non nostrud exercitation deserunt ea excepteur voluptate sunt velit ullamco non. Proident ut quis deserunt labore aliquip lorem tempor sit anim cillum non enim labore voluptate ex laboris reprehenderit ea. Ex non pariatur eu lorem eiusmod eu ex cupidatat ullamco pariatur occaecat enim.</p>',
          isConfirmed: true,
          medias: [
            {
              id: "260f3a9c-a56d-4d34-d383-08dc2864ac27",
              mediaType: "Photo",
              url: "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              thumbnailUrl:
                "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              description: null,
              order: 0,
            },
          ],
          links: [
            {
              id: "dd4a4968-a53a-4a8a-8bb7-08dc2864ac24",
              languageCode: "en",
              linkType: "Button",
              name: "Read More",
              url: "https://icloudhospital.com/read-more",
              isConfirmed: false,
              order: 0,
            },
          ],
          locations: [
            {
              id: "82e3d297-321c-46cd-63b7-08dc2864ac27",
              vender: "google",
              rating: 4.5,
              placeId: "google-place-id-here",
              order: 0,
            },
            {
              id: "30d61e52-44ba-4381-63b8-08dc2864ac27",
              vender: "facebook",
              rating: 3.5,
              placeId: "facebook-place-id-here",
              order: 1,
            },
          ],
        },
      ],
    },
    {
      id: "bf17927d-6226-446a-c47c-08dc2864ac22",
      listType: "Grid",
      customStyle: null,
      order: 3,
      blocks: [
        {
          id: "a75882bd-ad7f-4dfc-9b7f-08dc2864ac23",
          languageCode: "en",
          blockType: "Award",
          icon: null,
          customStyle: null,
          order: 0,
          name: "Award",
          subtitle: "",
          description: null,
          overview: "Consequat do ad officia sint est aliqua ea proident culpa",
          content: null,
          isConfirmed: true,
          medias: [
            {
              id: "4778a985-879d-4b18-d384-08dc2864ac27",
              mediaType: "Frontal",
              url: "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              thumbnailUrl:
                "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              description: null,
              order: 0,
            },
          ],
          links: [],
          locations: [],
        },
        {
          id: "4ba86ddb-b0f8-49bb-9b80-08dc2864ac23",
          languageCode: "en",
          blockType: "Award",
          icon: null,
          customStyle: null,
          order: 1,
          name: "Award",
          subtitle: "",
          description: null,
          overview:
            "Do occaecat sit velit magna enim proident mollit consequat",
          content: null,
          isConfirmed: true,
          medias: [
            {
              id: "3a31759e-ae52-4b2e-d385-08dc2864ac27",
              mediaType: "Frontal",
              url: "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              thumbnailUrl:
                "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              description: null,
              order: 0,
            },
          ],
          links: [],
          locations: [],
        },
        {
          id: "c59b32ca-fb07-46e3-9b81-08dc2864ac23",
          languageCode: "en",
          blockType: "Press",
          icon: null,
          customStyle: null,
          order: 2,
          name: "Press",
          subtitle: "",
          description: null,
          overview:
            "Aliquip officia cillum adipiscing commodo duis amet excepteur fugiat cupidatat cillum",
          content: null,
          isConfirmed: true,
          medias: [
            {
              id: "3a31759e-ae52-4b2e-d385-08dc2864ac27",
              mediaType: "Frontal",
              url: "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              thumbnailUrl:
                "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              description: null,
              order: 0,
            },
          ],
          links: [],
          locations: [],
        },
        {
          id: "c59b32ca-fb07-46e3-9b81-08dc2864ac23",
          languageCode: "en",
          blockType: "Press",
          icon: null,
          customStyle: null,
          order: 2,
          name: "Press",
          subtitle: "",
          description: null,
          overview:
            "Aliquip officia cillum adipiscing commodo duis amet excepteur fugiat cupidatat cillum",
          content: null,
          isConfirmed: true,
          medias: [
            {
              id: "3a31759e-ae52-4b2e-d385-08dc2864ac27",
              mediaType: "Frontal",
              url: "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              thumbnailUrl:
                "https://chblobdev.icloudhospital.com/thumbnails/2-26e5cd5d-7098-47cb-b541-8afdfce13d39.webp?w=1536&q=75&format=webp",
              description: null,
              order: 0,
            },
          ],
          links: [],
          locations: [],
        },
      ],
    },
  ],
  description: null,
  overview: null,
  content: null,
  id: "76b70ac1-ea13-44a1-1123-08dc2864ac1d",
  languageCode: "en",
  status: "Active",
  name: "Why Choose Us",
  slug: "why-choose-us",
  isConfirmed: true,
};
